import { Geist, Geist_Mono } from "next/font/google";
import { BracketProvider } from "@/context/BracketContext";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import RouteLoaderWrapper from "@/context/RouteLoaderWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <BracketProvider>
            <RouteLoaderWrapper>
              {children}
            </RouteLoaderWrapper>
          </BracketProvider>
        </AuthProvider>
        <Toaster position="top-center" toastOptions={{ duration: 3000}}/>
      </body>
    </html>
  );
}
