CREATE TABLE pools (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pool_name VARCHAR(255) NOT NULL,
    code VARCHAR(16) UNIQUE NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);