export const mockTeams = [
  { team_id: 1, team_name: 'UCLA', seed: 1, region: 'Spokane 1' },
  { team_id: 2, team_name: 'NC State', seed: 2, region: 'Spokane 1' },
  { team_id: 3, team_name: 'LSU', seed: 3, region: 'Spokane 1' },
  { team_id: 4, team_name: 'Baylor', seed: 4, region: 'Spokane 1' },
  { team_id: 5, team_name: 'Ole Miss', seed: 5, region: 'Spokane 1' },
  { team_id: 6, team_name: 'Florida St', seed: 6, region: 'Spokane 1' },
  { team_id: 7, team_name: 'Michigan St', seed: 7, region: 'Spokane 1' },
  { team_id: 8, team_name: 'Richmond', seed: 8, region: 'Spokane 1' },
  { team_id: 9, team_name: 'Georgia Tech', seed: 9, region: 'Spokane 1' },
  { team_id: 10, team_name: 'Harvard', seed: 10, region: 'Spokane 1' },
  { team_id: 11, team_name: 'George Mason', seed: 11, region: 'Spokane 1' },
  { team_id: 12, team_name: 'Ball St', seed: 12, region: 'Spokane 1' },
  { team_id: 13, team_name: 'Grand Canyon', seed: 13, region: 'Spokane 1' },
  { team_id: 14, team_name: 'San Diego St', seed: 14, region: 'Spokane 1' },
  { team_id: 15, team_name: 'Vermont', seed: 15, region: 'Spokane 1' },
  { team_id: 16, team_name: 'UC San Diego', seed: 16, region: 'Spokane 1' },
  { team_id: 17, team_name: 'Southern', seed: 16, region: 'Spokane 1' },
  { team_id: 18, team_name: 'South Carolina', seed: 1, region: 'Birmingham 2' },
  { team_id: 19, team_name: 'Duke', seed: 2, region: 'Birmingham 2' },
  { team_id: 20, team_name: 'North Carolina', seed: 3, region: 'Birmingham 2' },
  { team_id: 21, team_name: 'Maryland', seed: 4, region: 'Birmingham 2' },
  { team_id: 22, team_name: 'Alabama', seed: 5, region: 'Birmingham 2' },
  { team_id: 23, team_name: 'West Virginia', seed: 6, region: 'Birmingham 2' },
  { team_id: 24, team_name: 'Vanderbilt', seed: 7, region: 'Birmingham 2' },
  { team_id: 25, team_name: 'Utah', seed: 8, region: 'Birmingham 2' },
  { team_id: 26, team_name: 'Indiana', seed: 9, region: 'Birmingham 2' },
  { team_id: 27, team_name: 'Oregon', seed: 10, region: 'Birmingham 2' },
  { team_id: 28, team_name: 'Washington', seed: 11, region: 'Birmingham 2' },
  { team_id: 29, team_name: 'Columbia', seed: 11, region: 'Birmingham 2' },
  { team_id: 30, team_name: 'Green Bay', seed: 12, region: 'Birmingham 2' },
  { team_id: 31, team_name: 'Norfolk St', seed: 13, region: 'Birmingham 2' },
  { team_id: 32, team_name: 'Oregon St', seed: 14, region: 'Birmingham 2' },
  { team_id: 33, team_name: 'Lehigh', seed: 15, region: 'Birmingham 2' },
  { team_id: 34, team_name: 'Tennessee Tech', seed: 16, region: 'Birmingham 2' },
  { team_id: 35, team_name: 'Texas', seed: 1, region: 'Birmingham 3' },
  { team_id: 36, team_name: 'TCU', seed: 2, region: 'Birmingham 3' },
  { team_id: 37, team_name: 'Notre Dame', seed: 3, region: 'Birmingham 3' },
  { team_id: 38, team_name: 'Ohio State', seed: 4, region: 'Birmingham 3' },
  { team_id: 39, team_name: 'Tennessee', seed: 5, region: 'Birmingham 3' },
  { team_id: 40, team_name: 'Michigan', seed: 6, region: 'Birmingham 3' },
  { team_id: 41, team_name: 'Louisville', seed: 7, region: 'Birmingham 3' },
  { team_id: 42, team_name: 'Illinois', seed: 8, region: 'Birmingham 3' },
  { team_id: 43, team_name: 'Creighton', seed: 9, region: 'Birmingham 3' },
  { team_id: 44, team_name: 'Nebraska', seed: 10, region: 'Birmingham 3' },
  { team_id: 45, team_name: 'Iowa State', seed: 11, region: 'Birmingham 3' },
  { team_id: 46, team_name: 'Princeton', seed: 11, region: 'Birmingham 3' },
  { team_id: 47, team_name: 'South Florida', seed: 12, region: 'Birmingham 3' },
  { team_id: 48, team_name: 'Montana St', seed: 13, region: 'Birmingham 3' },
  { team_id: 49, team_name: 'SF Austin', seed: 14, region: 'Birmingham 3' },
  { team_id: 50, team_name: 'Fair Dickinson', seed: 15, region: 'Birmingham 3' },
  { team_id: 51, team_name: 'High Point', seed: 16, region: 'Birmingham 3' },
  { team_id: 52, team_name: 'William & Mary', seed: 16, region: 'Birmingham 3' },
  { team_id: 53, team_name: 'USC', seed: 1, region: 'Spokane 4' },
  { team_id: 54, team_name: 'UCONN', seed: 2, region: 'Spokane 4' },
  { team_id: 55, team_name: 'Oklahoma', seed: 3, region: 'Spokane 4' },
  { team_id: 56, team_name: 'Kentucky', seed: 4, region: 'Spokane 4' },
  { team_id: 57, team_name: 'Kansas St', seed: 5, region: 'Spokane 4' },
  { team_id: 58, team_name: 'Iowa', seed: 6, region: 'Spokane 4' },
  { team_id: 59, team_name: 'Oklahoma St', seed: 7, region: 'Spokane 4' },
  { team_id: 60, team_name: 'California', seed: 8, region: 'Spokane 4' },
  { team_id: 61, team_name: 'Mississippi St', seed: 9, region: 'Spokane 4' },
  { team_id: 62, team_name: 'S Dakota St', seed: 10, region: 'Spokane 4' },
  { team_id: 63, team_name: 'Murray St', seed: 11, region: 'Spokane 4' },
  { team_id: 64, team_name: 'Fairfield', seed: 12, region: 'Spokane 4' },
  { team_id: 65, team_name: 'Liberty', seed: 13, region: 'Spokane 4' },
  { team_id: 66, team_name: 'FGCU', seed: 14, region: 'Spokane 4' },
  { team_id: 67, team_name: 'Arkansas St', seed: 15, region: 'Spokane 4' },
  { team_id: 68, team_name: 'UNC Greensboro', seed: 16, region: 'Spokane 4' },
];
